// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvuium_zR4dB3WWYY1S1lB_J9Xsg72-A',
    appId: '1:355453052992:web:c7d78e6b4cbddfbf0657a5',
    messagingSenderId: '355453052992',
    projectId: 'kurbanku-terencana',
    authDomain: 'kurbanku-terencana.firebaseapp.com',
    storageBucket: 'kurbanku-terencana.firebasestorage.app',
    measurementId: 'G-ZE70ZE88V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG35IahTBZCtiEiXAw3lO2BfOJ2-qhMjw',
    appId: '1:355453052992:android:90bc616f084aee600657a5',
    messagingSenderId: '355453052992',
    projectId: 'kurbanku-terencana',
    storageBucket: 'kurbanku-terencana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeVC4QJNALDiX8P2CQL_GbeWkjjmiRcJA',
    appId: '1:355453052992:ios:927e158c32f0b26d0657a5',
    messagingSenderId: '355453052992',
    projectId: 'kurbanku-terencana',
    storageBucket: 'kurbanku-terencana.firebasestorage.app',
    iosBundleId: 'com.example.kurbankuTerencana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeVC4QJNALDiX8P2CQL_GbeWkjjmiRcJA',
    appId: '1:355453052992:ios:927e158c32f0b26d0657a5',
    messagingSenderId: '355453052992',
    projectId: 'kurbanku-terencana',
    storageBucket: 'kurbanku-terencana.firebasestorage.app',
    iosBundleId: 'com.example.kurbankuTerencana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLvuium_zR4dB3WWYY1S1lB_J9Xsg72-A',
    appId: '1:355453052992:web:7adc57abe0b182510657a5',
    messagingSenderId: '355453052992',
    projectId: 'kurbanku-terencana',
    authDomain: 'kurbanku-terencana.firebaseapp.com',
    storageBucket: 'kurbanku-terencana.firebasestorage.app',
    measurementId: 'G-QTMXTHWHE2',
  );
}
